package v20.Common;

import java.io.IOException;
import java.lang.reflect.Field;
import java.util.Enumeration;
import java.util.Properties;

public class Config extends java.util.Properties {
    @Override
    public String getProperty(String key) {
        String value = super.getProperty(key);
        if (value == null) {
            throw new RuntimeException("Unknown property " + key);
        }
        return value;
    }

    static Properties pro;

    static {
        try {
            pro = base.Common.getConfig(base.Config.APPCONFIG_PATH);
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    public static final String RUN_FROM_TESTPLAN = pro.getProperty("runFromTestPlan");
    public static final String SUITE_APPNAME = pro.getProperty("suite.appName");

    public static final String CUCUMBER_OPTION_FEATURES = pro.getProperty("cucumber.option.features");
    public static final String CUCUMBER_OPTION_GLUE = pro.getProperty("cucumber.option.glue");
    // public static final String OS_NAME=System.getProperty("os.name");
    public static final String driverPerFeature = pro.getProperty("opendriverPerFeature");
    public static final String CUCUMBER_OPTION_TAGS = pro.getProperty("cucumber.option.tags");
    public static String DATA_TABLE_FILE_PATH;
    public static String DATA_TABLE_FILE_NAME_QA = pro.getProperty("dataTableFileName_QA");
    public static String DATA_TABLE_FILE_NAME_DEV1 = pro.getProperty("dataTableFileName_dev1");
    public static String DATA_TABLE_FILE_NAME_UAT = pro.getProperty("dataTableFileName_UAT");
    public static String DATA_TABLE_FILE_NAME_PREPROD = pro.getProperty("dataTableFileName_PREPROD");
    public static String DATA_TABLE_FILE_NAME_V20SB = pro.getProperty("dataTableFileName_V20SB");

    public static String chromeOption_ImageBlocked = pro.getProperty("chromeOption.ImageLoadBlocked");

    public static final String defaultdownloaddirEIS = pro.getProperty("defaultdownloaddirEIS");
    public static final String isDriverHeadless = pro.getProperty("driver.option.headless");
    public static final String migrationOutputTemplatepath = pro.getProperty("migrationOutputTemplatepath");
    public static final String migrationlogFilepath = pro.getProperty("migrationlogFilepath");
    public static final String migrationOutputDirectory = pro.getProperty("migrationOutputDirectory");
    //  public static String HOST_NAME;
    //public static final String ENV=pro.getProperty("environment");
    public static String ENV;//= FeatureDriver.env;
    public static String URL;
    public static String userName;
    public static String PreSaluserName;
    public static String PreSalpassWord;

    public static String urllogoff = pro.getProperty("urlLogoff");
    public static String passWord;
    public static String SSOSuperuserName;
    public static String SSOAdminuserName;

    public static String PSAuserName;
    public static String ConservationAnalystuserName;
    public static String ConservationAnalystpassWord;
    public static String UW4userName;
    public static String UW3userName;
    public static String UW3passWord;
    public static String UW2userName;
    public static String UW2passWord;
    public static String UW1userName;
    public static String UW1passWord;

    public static String UWTraineeuserName;

    public static String UnderwritingName;

    public static String UWAuserName;

    public static String UWpassword;
    public static String PSApassWord;
    public static String UW4passWord;
    public static String SSOpassWord;
    public static String UW1_UserName;//= pro.getProperty("qa.uw1.username");
    public static String UW1_Pwd;//= pro.getProperty("qa.uw1.password");
    public static String UW2_UserName;// = pro.getProperty("qa.uw2.username");
    public static String UW2_Pwd;//= pro.getProperty("qa.uw2.password");
    public static String RB_PreSales_UN;
    public static String RB_PreSales_Pwd;
    public static String RB_SalesRepIndividual_UN;
    public static String RB_SalesRepIndividual_Pwd;
    public static String RB_Underwriting1_UN;
    public static String RB_Underwriting1_Pwd;
    public static String RB_SystemAdmin_UN;
    public static String RB_SystemAdmin_Pwd;
    public static String RB_SuperUser_UN;
    public static String RB_SuperUser_Pwd;
    public static String RB_SalesRepRSO_UN;
    public static String RB_SalesRepRSO_Pwd;
    public static String RB_SalesRepRegion_UN;
    public static String RB_SalesRepRegion_Pwd;
    public static String RB_SalesRepGlobal_UN;
    public static String RB_SalesRepGlobal_Pwd;
    public static String SuperUserSSO_UN;
    public static String SuperUserSSO_PW;

    public static String userSleepMS = pro.getProperty("user.sleep.ms");
    public static final long driverWaitTime = Long.parseLong(pro.getProperty("driver.wait.sec"));
    public static final long sleepTimeInterval = Long.parseLong(pro.getProperty("poolinterval"));

    public static final String CustomerDatafilePath_HI = pro.getProperty("customerDatafilepath_HI");
    public static final String CustomerDatafilePath_AC = pro.getProperty("customerDatafilepath_AC");
    public static final String CustomerDatafilePath_CI = pro.getProperty("customerDatafilepath_CI");

    public static final String CustomerDatafilePath_STD_VPS = pro.getProperty("customerDatafilepath_STD_VPS");

    //    public static final String CustomerDatafilePath_LTD_VPL = pro.getProperty("customerDatafilepath_LTD_VPL");
    public static final String CustomerDatafilePath_STD_STD = pro.getProperty("customerDatafilepath_STD_STD");
    public static final String CustomerDatafilePath_STD_ASW = pro.getProperty("customerDatafilepath_STD_ASW");
    public static final String CustomerDatafilePath_LTD_LTD = pro.getProperty("customerDatafilepath_LTD");
    public static final String CustomerDatafilePath_SMP_ORL = pro.getProperty("CustomerDatafilePath_SMP_ORL");
    public static final String CustomerDatafilePath_LTD_VPL = pro.getProperty("customerDatafilepath_LTD_VPL");

    public static final String CustomerDatafilePath_LTD_ASL = pro.getProperty("customerDatafilepath_LTD_ASL");
    public static final String CustomerDatafilePath_GTL_VAR = pro.getProperty("customerDatafilepath_GTL_VAR");
    public static final String CustomerDatafilePath_GTL_VG = pro.getProperty("customerDatafilepath_GTL_VG");
    public static final String CustomerDatafilePath_GTL_GL = pro.getProperty("customerDatafilepath_GTL_GL");

    public static final String CustomerDatafileName_LTD_LTD = pro.getProperty("CustomerDatafileName_LTD");


    public static final String CustomerDatafileName_LTD_VPL = pro.getProperty("CustomerDatafileName_LTD_VPL");
    public static final String CustomerDatafileName_LTD_ASL = pro.getProperty("CustomerDatafileName_LTD_ASL");
    public static final String CustomerDatafileName_GTL_VAR = pro.getProperty("CustomerDatafileName_GTL_VAR");
    public static final String CustomerDatafileName_GTL_VG = pro.getProperty("CustomerDatafileName_GTL_VG");
    public static final String CustomerDatafileName_GTL_GL = pro.getProperty("CustomerDatafileName_GTL_GL");
    public static final String CustomerDatafileName_HI = pro.getProperty("customerDatafilname_HI");
    public static final String CustomerDatafileName_AC = pro.getProperty("customerDatafilname_AC");
    public static final String CustomerDatafileName_CI = pro.getProperty("customerDatafilname_CI");
    public static final String CustomerDatafileName_STD_STD = pro.getProperty("customerDatafilname_STD_STD");

    public static final String CustomerDatafilePath_SMP_TDB = pro.getProperty("CustomerDatafilePath_SMP_TDB");
    public static final String CustomerDatafilePath_SMP_TDI = pro.getProperty("CustomerDatafilePath_SMP_TDI");
    public static final String CustomerDatafilePath_SMP_MAL = pro.getProperty("CustomerDatafilePath_SMP_MAL");
    public static final String CustomerDatafilePath_SMP_CTL = pro.getProperty("CustomerDatafilePath_SMP_CTL");
    public static final String CustomerDatafilePath_SMP_COL = pro.getProperty("CustomerDatafilePath_SMP_COL");

    public static final String CustomerDatafilePath_SMP_CVP = pro.getProperty("CustomerDatafilePath_SMP_CVP");
    public static final String CustomerDatafilePath_SMP_WAV = pro.getProperty("CustomerDatafilePath_SMP_WAV");
    public static final String CustomerDatafilePath_SMP_DBL = pro.getProperty("CustomerDatafilePath_SMP_DBL");
    public static final String CustomerDatafilePath_SMP_MEL = pro.getProperty("CustomerDatafilePath_SMP_MEL");
    public static final String CustomerDatafilePath_Leave_FML = pro.getProperty("CustomerDatafilePath_Leave_FML");
    public static final String CustomerDatafilePath_Leave_LOA = pro.getProperty("CustomerDatafilePath_Leave_LOA");
    public static final String CustomerDatafilePath_Leave_PLA = pro.getProperty("CustomerDatafilePath_Leave_PLA");
    public static final String CustomerDatafilePath_Leave_ADA = pro.getProperty("CustomerDatafilePath_Leave_ADA");
    public static final String CustomerDatafileName_SMP_ORL = pro.getProperty("customerDatafilename_SMP_ORL");
    public static final String CustomerDatafileName_SMP_MEL = pro.getProperty("customerDatafilename_SMP_MEL");
    public static final String CustomerDatafileName_SMP_COL = pro.getProperty("customerDatafilename_SMP_COL");
    public static final String CustomerDatafileName_SMP_TDB = pro.getProperty("customerDatafilename_SMP_TDB");
    public static final String CustomerDatafileName_SMP_TDI = pro.getProperty("customerDatafilename_SMP_TDI");
    public static final String CustomerDatafileName_SMP_MAL = pro.getProperty("customerDatafilename_SMP_MAL");
    public static final String CustomerDatafileName_SMP_CTL = pro.getProperty("customerDatafilename_SMP_CTL");

    public static final String CustomerDatafileName_SMP_CVP = pro.getProperty("customerDatafilename_SMP_CVP");
    public static final String CustomerDatafileName_SMP_WAV = pro.getProperty("customerDatafilename_SMP_WAV");
    public static final String CustomerDatafileName_SMP_DBL = pro.getProperty("customerDatafilename_SMP_DBL");

    public static final String CustomerDatafileName_STD_VPS = pro.getProperty("customerDatafilname_STD_VPS");

    public static final String CustomerDatafileName_STD_AWS = pro.getProperty("customerDatafilname_STD_AWS");

    public static final String CustomerDatafileName_Leave_FML = pro.getProperty("CustomerDatafileName_Leave_FML");
    public static final String CustomerDatafileName_Leave_LOA = pro.getProperty("CustomerDatafileName_Leave_LOA");
    public static final String CustomerDatafileName_Leave_PLA = pro.getProperty("CustomerDatafileName_Leave_PLA");
    public static final String CustomerDatafileName_Leave_ADA = pro.getProperty("CustomerDatafileName_Leave_ADA");
//    public static final String AgencyPACSDbData = pro.getProperty("AgencyPACSDbData");
//    public static final String VUEDBData = pro.getProperty("VUEDBData");
//    public static final String APSDBData = pro.getProperty("APSDBData");
//    public static final String STACSDBData = pro.getProperty("STACSDBData");

    public static String urllogout = pro.getProperty("urllogout");

    public static final String DynamicDataTemplatefilePath = Config.pro.getProperty("dynamicDataTemplatepath");
    public static final String customerurlpart = pro.getProperty("urlCustomerpagepart");
    public static final String deletedynamicdatafile = pro.getProperty("deletedynamicdatafile");
    public static final String dataArchiveDirpath = pro.getProperty("dataArchiveDirpath");
    public static final String HOST_NAME;
    public static String rslsfURL; //= pro.getProperty("rsosf.url");
    public static String rslsfUN; //= pro.getProperty("rsosf.username");
    public static String rslsfPWD; //= pro.getProperty("rsosf.password");
    public static String easURL;// = pro.getProperty("eas.url");
    public static String easUN; //= pro.getProperty("eas.username");
    public static String easPWD; //= pro.getProperty("eas.password");
    public static String pacsDBDriver;
    public static String pacsDBUN;
    public static String pacsDBPWD;
    public static String pacsDBURLr;

/*    public static String V20SBURL;
    public static String V20SBUN;
    public static String V20SBPWD;*/

    public static String eserviceURL;
    public static String eserviceUN;
    public static String eservicePWD;

    public static String apsDBDriver;
    public static String apsDBUN;
    public static String apsDBPWD;
    public static String apsDBURLr;

    public static String vueDBDriver;
    public static String vueDBUN;
    public static String vueDBPWD;
    public static String vueDBURLr;

/*    public static String vueDBDriver=pro.getProperty("qa.VUE.DB.driver");
    public static String vueDBUN=pro.getProperty("qa.VUE.DB.username");
    public static String vueDBPWD=pro.getProperty("qa.VUE.DB.password");
    public static String vueDBURLr=pro.getProperty("qa.VUE.DB.url");*/

    public static String stacsinterimDBDriver;
    public static String stacsinterimDBUN;
    public static String stacsinterimDBPWD;
    public static String stacsinterimDBURLr;

    public static String stacsDBDriver;
    public static String stacsDBUN;
    public static String stacsDBPWD;
    public static String stacsDBURLr;

    public static String eisDBDriver;
    public static String eisDBUN;
    public static String eisDBPWD;
    public static String eisDBURLr;

    public static final String dynamicdatafolderpath = pro.getProperty("dynamicdatafolderpath");
    public static String dynamicdatafoldersharedpath;

    public static String dynamicdatafoldersharedpathQS;

    public static String dynamicdatafoldersharedpathSB;

    public static String dynamicdatafoldersharedpathCV;

    public static String customerPacsURLSuffix;
    public static String customerOpportunityURLSuffix;
    public static String searchPolicyURLSuffix;

    //static Logger log= LogManager.getLogger(Config.class);
    static {
        HOST_NAME = base.Config.HOST_NAME;//getLocalHost().getHostName();
 /*       if(ENV.trim().equalsIgnoreCase("qa")) {
            URL = pro.getProperty("qa.url");
            userName=pro.getProperty("qa.username");
            passWord=pro.getProperty("qa.password");
            UW1_UserName = pro.getProperty("qa.uw1.username");
            UW1_Pwd = pro.getProperty("qa.uw1.password");
            UW2_UserName = pro.getProperty("qa.uw2.username");
            UW2_Pwd = pro.getProperty("qa.uw2.password");
        }else if(ENV.trim().equalsIgnoreCase("uat")){
            URL = pro.getProperty("uat.url");
            userName=pro.getProperty("uat.username");
            passWord=pro.getProperty("uat.password");
            UW1_UserName = pro.getProperty("uat.uw1.username");
            UW1_Pwd = pro.getProperty("uat.uw1.password");
            UW2_UserName = pro.getProperty("uat.uw2.username");
            UW2_Pwd = pro.getProperty("uat.uw2.password");
        }else if(ENV.trim().equalsIgnoreCase("stage")){
            URL = pro.getProperty("stage.url");
            userName = pro.getProperty("stage.username");
            passWord = pro.getProperty("stage.password");
            UW1_UserName = pro.getProperty("stage.uw1.username");
            UW1_Pwd = pro.getProperty("stage.uw1.password");
            UW2_UserName = pro.getProperty("stage.uw2.username");
            UW2_Pwd = pro.getProperty("stage.uw2.password");
        }else{
            URL = pro.getProperty("qa.url");
            userName=pro.getProperty("qa.username");
            passWord=pro.getProperty("qa.password");
            UW1_UserName = pro.getProperty("qa.uw1.username");
            UW1_Pwd = pro.getProperty("qa.uw1.password");
            UW2_UserName = pro.getProperty("qa.uw2.username");
            UW2_Pwd = pro.getProperty("qa.uw2.password");
        }*/
    }

    public Config(String environment) throws Exception {
        if (chromeOption_ImageBlocked == null || chromeOption_ImageBlocked.trim().equalsIgnoreCase("") || chromeOption_ImageBlocked.trim().equalsIgnoreCase("1")) {
            base.Common.chromeOptionImageBlocked = 1;
        } else if (chromeOption_ImageBlocked.trim().equalsIgnoreCase("0")) {
            base.Common.chromeOptionImageBlocked = 0;
        } else {
            base.Common.chromeOptionImageBlocked = 2;
        }
        ENV = environment;
        if (SUITE_APPNAME.contains("EIS")) {
            base.Common.appName = "eis";
        }
        if (environment.equalsIgnoreCase("QA") || environment.equalsIgnoreCase("DEV")
                || environment.equalsIgnoreCase("mqa")) {
            System.out.println("envrironment-->" + Config.ENV);
            customerPacsURLSuffix = pro.getProperty("eis.customer.pacs.url.suffix");
            customerOpportunityURLSuffix = pro.getProperty("eis.customer.opportunity.url.suffix");
            searchPolicyURLSuffix = pro.getProperty("eis.customer.policySearch.produrl.suffix");
        } else if (environment.equalsIgnoreCase("preprod") || environment.equalsIgnoreCase("uat") ||
                environment.equalsIgnoreCase("preprodphase1")) {
            System.out.println("EnvironmentPreprod/uat");
            customerPacsURLSuffix = pro.getProperty("eis.customer.pacs.produrl.suffix");
            System.out.println("customerPacsURLSuffix-->" + pro.getProperty("eis.customer.pacs.produrl.suffix"));
            customerOpportunityURLSuffix = pro.getProperty("eis.customer.opportunity.url.suffix");
            searchPolicyURLSuffix = pro.getProperty("eis.customer.policySearch.produrl.suffix");
        }
        if (ENV.trim().equalsIgnoreCase("dev")) {
            System.out.println("StartDev");
            DATA_TABLE_FILE_PATH = base.Config.DATATABLE_ROOT_PATH + DATA_TABLE_FILE_NAME_DEV1;
            System.out.println("Dev Data table path: " + DATA_TABLE_FILE_PATH);
            base.Config.DATATABLE_FILE_PATH = DATA_TABLE_FILE_PATH;
            URL = pro.getProperty("dev.url");
            userName = pro.getProperty("dev.username");
            passWord = pro.getProperty("dev.password");
            SSOSuperuserName = pro.getProperty("qa.ssoSuperusername");
            SSOpassWord = pro.getProperty("qa.ssopassword");
            PreSaluserName = pro.getProperty("qa.PreSaleurname");
            PreSalpassWord = pro.getProperty("qa.PreSalepassword");
            PSAuserName = pro.getProperty("qa.PSAusername");
            PSApassWord = pro.getProperty("qa.PSApassword");
            UW4userName = pro.getProperty("qa.UW4username");
            UW3userName = pro.getProperty("qa.UW3username");
            UW2userName = pro.getProperty("qa.UW2username");
            UW1userName = pro.getProperty("qa.UW1username");
            UnderwritingName = pro.getProperty("qa.UnderwritingName");
            UWTraineeuserName = pro.getProperty("qa.UWTraineeusername");
            UWAuserName = pro.getProperty("qa.UWAssistantusername");
            UWpassword = pro.getProperty("qa.UWpassword");
            UW1_UserName = pro.getProperty("qa.uw1.username");
            UW1_Pwd = pro.getProperty("qa.uw1.password");
            UW2_UserName = pro.getProperty("qa.uw2.username");
            UW2_Pwd = pro.getProperty("qa.uw2.password");
            RB_PreSales_UN = pro.getProperty("qa.presalsebasic.username");
            RB_PreSales_Pwd = pro.getProperty("qa.presalsebasic.password");
            RB_SalesRepIndividual_UN = pro.getProperty("qa.salesrepindividual.username");
            RB_SalesRepIndividual_Pwd = pro.getProperty("qa.salesrepindividual.password");
            RB_Underwriting1_UN = pro.getProperty("qa.Underwriting1.username");
            RB_Underwriting1_Pwd = pro.getProperty("qa.Underwriting1.password");
            RB_SystemAdmin_UN = pro.getProperty("qa.sysadmin.username");
            RB_SystemAdmin_Pwd = pro.getProperty("qa.sysadmin.password");
            RB_SuperUser_UN = pro.getProperty("qa.superuser.username");
            RB_SuperUser_Pwd = pro.getProperty("qa.superuser.password");
            RB_SalesRepRSO_UN = pro.getProperty("qa.salesreprso.username");
            RB_SalesRepRSO_Pwd = pro.getProperty("qa.salesreprso.password");
            RB_SalesRepRegion_UN = pro.getProperty("qa.salesrepsalesrepregion.username");
            RB_SalesRepRegion_Pwd = pro.getProperty("qa.salesrepsalesrepregion.password");
            RB_SalesRepGlobal_UN = pro.getProperty("qa.SalesRepGlobal.username");
            RB_SalesRepGlobal_Pwd = pro.getProperty("qa.SalesRepGlobal.password");
            rslsfURL = pro.getProperty("qa.rslsf.url");
            rslsfUN = pro.getProperty("qa.rslsf.username");
            rslsfPWD = pro.getProperty("qa.rslsf.password");
            easURL = pro.getProperty("qa.eas.url");
            easUN = pro.getProperty("qa.eas.username");
            easPWD = pro.getProperty("qa.eas.password");
            pacsDBDriver = pro.getProperty("dev.PACS.DB.driver");
            pacsDBUN = pro.getProperty("dev.PACS.DB.username");
            pacsDBPWD = pro.getProperty("dev.PACS.DB.password");
            pacsDBURLr = pro.getProperty("dev.PACS.DB.url");
            apsDBDriver = pro.getProperty("qa.APS.DB.driver");
            apsDBUN = pro.getProperty("qa.APS.DB.username");
            apsDBPWD = pro.getProperty("qa.APS.DB.password");
            apsDBURLr = pro.getProperty("qa.APS.DB.url");
            vueDBDriver = pro.getProperty("qa.VUE.DB.driver");
            vueDBUN = pro.getProperty("qa.VUE.DB.username");
            vueDBPWD = pro.getProperty("qa.VUE.DB.password");
            vueDBURLr = pro.getProperty("qa.VUE.DB.url");
            stacsinterimDBDriver = pro.getProperty("qa.STACSINTERIM.DB.driver");
            stacsinterimDBUN = pro.getProperty("qa.STACSINTERIM.DB.username");
            stacsinterimDBPWD = pro.getProperty("qa.STACSINTERIM.DB.password");
            stacsinterimDBURLr = pro.getProperty("qa.STACSINTERIM.DB.url");
            stacsDBDriver = pro.getProperty("qa.STACS.DB.driver");
            stacsDBUN = pro.getProperty("qa.STACS.DB.username");
            stacsDBPWD = pro.getProperty("qa.STACS.DB.password");
            stacsDBURLr = pro.getProperty("qa.STACS.DB.url");
//            dynamicdatafoldersharedpath = pro.getProperty("dev.e2e.dynamicdatafoldersharedpath");
            dynamicdatafoldersharedpathCV = pro.getProperty("dev.e2e.dynamicdatafoldersharedpathCV");
            dynamicdatafoldersharedpathQS = pro.getProperty("dev.e2e.q2s.dynamicdatafoldersharedpath");
            dynamicdatafoldersharedpathSB = pro.getProperty("dev.e2e.s2b.dynamicdatafoldersharedpath");
        } else if (ENV.trim().equalsIgnoreCase("qa")) {
            DATA_TABLE_FILE_PATH = base.Config.DATATABLE_ROOT_PATH + DATA_TABLE_FILE_NAME_QA;
            System.out.println("qa Data table path: " + DATA_TABLE_FILE_PATH);
            base.Config.DATATABLE_FILE_PATH = DATA_TABLE_FILE_PATH;
//            URL = pro.getProperty("qa.url");
//            userName = pro.getProperty("qa.username");
//            passWord = pro.getProperty("qa.password");
            URL = pro.getProperty("ac.url");
            userName = pro.getProperty("ac.username");
            passWord = pro.getProperty("ac.password");
            PreSaluserName = pro.getProperty("qa.PreSaleurname");
            PreSalpassWord = pro.getProperty("qa.PreSalepassword");
            PSAuserName = pro.getProperty("qa.PSAusername");
            PSApassWord = pro.getProperty("qa.PSApassword");
            UW4userName = pro.getProperty("qa.UW4username");
            UW3userName = pro.getProperty("qa.UW3username");
            UW2userName = pro.getProperty("qa.UW2username");
            UW1userName = pro.getProperty("qa.UW1username");
            UnderwritingName = pro.getProperty("qa.UnderwritingName");
            UWTraineeuserName = pro.getProperty("qa.UWTraineeusername");
            UWAuserName = pro.getProperty("qa.UWAssistantusername");
            UWpassword = pro.getProperty("qa.UWpassword");
            ConservationAnalystuserName = pro.getProperty("qa.ConservationAnalystusernam");
            ConservationAnalystpassWord = pro.getProperty("qa.ConservationAnalystpassword");
            SSOAdminuserName = pro.getProperty("qa.ssoAdminusername");
            UW1_UserName = pro.getProperty("qa.uw1.username");
            UW1_Pwd = pro.getProperty("qa.uw1.password");
            UW2_UserName = pro.getProperty("qa.uw2.username");
            UW2_Pwd = pro.getProperty("qa.uw2.password");
            SSOSuperuserName = pro.getProperty("qa.ssoSuperusername");
            SSOpassWord = pro.getProperty("qa.ssopassword");
            RB_PreSales_UN = pro.getProperty("qa.presalsebasic.username");
            RB_PreSales_Pwd = pro.getProperty("qa.presalsebasic.password");
            RB_SalesRepIndividual_UN = pro.getProperty("qa.salesrepindividual.username");
            RB_SalesRepIndividual_Pwd = pro.getProperty("qa.salesrepindividual.password");
            RB_Underwriting1_UN = pro.getProperty("qa.Underwriting1.username");
            RB_Underwriting1_Pwd = pro.getProperty("qa.Underwriting1.password");
            RB_SystemAdmin_UN = pro.getProperty("qa.sysadmin.username");
            RB_SystemAdmin_Pwd = pro.getProperty("qa.sysadmin.password");
            RB_SuperUser_UN = pro.getProperty("qa.superuser.username");
            RB_SuperUser_Pwd = pro.getProperty("qa.superuser.password");
            RB_SalesRepRSO_UN = pro.getProperty("qa.salesreprso.username");
            RB_SalesRepRSO_Pwd = pro.getProperty("qa.salesreprso.password");
            RB_SalesRepRegion_UN = pro.getProperty("qa.salesrepsalesrepregion.username");
            RB_SalesRepRegion_Pwd = pro.getProperty("qa.salesrepsalesrepregion.password");
            RB_SalesRepGlobal_UN = pro.getProperty("qa.SalesRepGlobal.username");
            RB_SalesRepGlobal_Pwd = pro.getProperty("qa.SalesRepGlobal.password");
            SuperUserSSO_UN = pro.getProperty("qa.SuperUserSSO_UN.username");
            SuperUserSSO_PW = pro.getProperty("qa.SuperUserSSO_PW.password");
            rslsfURL = pro.getProperty("qa.rslsf.url");
            rslsfUN = pro.getProperty("qa.rslsf.username");
            rslsfPWD = pro.getProperty("qa.rslsf.password");
            easURL = pro.getProperty("qa.eas.url");
            easUN = pro.getProperty("qa.eas.username");
            easPWD = pro.getProperty("qa.eas.password");
            pacsDBDriver = pro.getProperty("qa.PACS.DB.driver");
            pacsDBUN = pro.getProperty("qa.PACS.DB.username");
            pacsDBPWD = pro.getProperty("qa.PACS.DB.password");
            pacsDBURLr = pro.getProperty("qa.PACS.DB.url");
            apsDBDriver = pro.getProperty("qa.APS.DB.driver");
            apsDBUN = pro.getProperty("qa.APS.DB.username");
            apsDBPWD = pro.getProperty("qa.APS.DB.password");
            apsDBURLr = pro.getProperty("qa.APS.DB.url");
            vueDBDriver = pro.getProperty("qa.VUE.DB.driver");
            vueDBUN = pro.getProperty("qa.VUE.DB.username");
            vueDBPWD = pro.getProperty("qa.VUE.DB.password");
            vueDBURLr = pro.getProperty("qa.VUE.DB.url");
            stacsinterimDBDriver = pro.getProperty("qa.STACSINTERIM.DB.driver");
            stacsinterimDBUN = pro.getProperty("qa.STACSINTERIM.DB.username");
            stacsinterimDBPWD = pro.getProperty("qa.STACSINTERIM.DB.password");
            stacsinterimDBURLr = pro.getProperty("qa.STACSINTERIM.DB.url");
            stacsDBDriver = pro.getProperty("qa.STACS.DB.driver");
            stacsDBUN = pro.getProperty("qa.STACS.DB.username");
            stacsDBPWD = pro.getProperty("qa.STACS.DB.password");
            stacsDBURLr = pro.getProperty("qa.STACS.DB.url");
            eisDBDriver = pro.getProperty("EIS.DB.driver");
            eisDBUN = pro.getProperty("EIS.DB.username");
            eisDBPWD = pro.getProperty("EIS.DB.password");
            eisDBURLr = pro.getProperty("EIS.DB.url");
//            dynamicdatafoldersharedpath = pro.getProperty("qa.e2e.dynamicdatafoldersharedpath");
            dynamicdatafoldersharedpathCV = pro.getProperty("qa.e2e.dynamicdatafoldersharedpathCV");
            dynamicdatafoldersharedpathQS = pro.getProperty("qa.e2e.q2s.dynamicdatafoldersharedpath");
            dynamicdatafoldersharedpathSB = pro.getProperty("qa.e2e.s2b.dynamicdatafoldersharedpath");
        } else if (ENV.trim().equalsIgnoreCase("uat")) {
            DATA_TABLE_FILE_PATH = base.Config.DATATABLE_ROOT_PATH + DATA_TABLE_FILE_NAME_UAT;
            System.out.println("uat Data table path: " + DATA_TABLE_FILE_PATH);
            base.Config.DATATABLE_FILE_PATH = DATA_TABLE_FILE_PATH;
            URL = pro.getProperty("uat.url");
            userName = pro.getProperty("uat.username");
            passWord = pro.getProperty("uat.password");
            PreSaluserName = pro.getProperty("qa.PreSaleurname");
            PreSalpassWord = pro.getProperty("qa.PreSalepassword");
            SSOSuperuserName = pro.getProperty("uat.ssoSuperusername");
            SSOpassWord = pro.getProperty("uat.ssopassword");
            UW1_UserName = pro.getProperty("uat.uw1.username");
            UW1_Pwd = pro.getProperty("uat.uw1.password");
            UW2_UserName = pro.getProperty("uat.uw2.username");
            UW2_Pwd = pro.getProperty("uat.uw2.password");
            UW4userName = pro.getProperty("qa.UW4username");
            UWpassword = pro.getProperty("qa.UWpassword");
            rslsfURL = pro.getProperty("uat.rslsf.url");
            rslsfUN = pro.getProperty("uat.rslsf.username");
            rslsfPWD = pro.getProperty("uat.rslsf.password");
            easURL = pro.getProperty("uat.eas.url");
            easUN = pro.getProperty("uat.eas.username");
            easPWD = pro.getProperty("uat.eas.password");
            pacsDBDriver = pro.getProperty("uat.PACS.DB.driver");
            pacsDBUN = pro.getProperty("uat.PACS.DB.username");
            pacsDBPWD = pro.getProperty("uat.PACS.DB.password");
            pacsDBURLr = pro.getProperty("uat.PACS.DB.url");
            apsDBDriver = pro.getProperty("uat.APS.DB.driver");
            apsDBUN = pro.getProperty("uat.APS.DB.username");
            apsDBPWD = pro.getProperty("uat.APS.DB.password");
            apsDBURLr = pro.getProperty("uat.APS.DB.url");
            vueDBDriver = pro.getProperty("uat.VUE.DB.driver");
            vueDBUN = pro.getProperty("uat.VUE.DB.username");
            vueDBPWD = pro.getProperty("uat.VUE.DB.password");
            vueDBURLr = pro.getProperty("uat.VUE.DB.url");
            stacsinterimDBDriver = pro.getProperty("uat.STACSINTERIM.DB.driver");
            stacsinterimDBUN = pro.getProperty("uat.STACSINTERIM.DB.username");
            stacsinterimDBPWD = pro.getProperty("uat.STACSINTERIM.DB.password");
            stacsinterimDBURLr = pro.getProperty("uat.STACSINTERIM.DB.url");
            stacsDBDriver = pro.getProperty("uat.STACS.DB.driver");
            stacsDBUN = pro.getProperty("uat.STACS.DB.username");
            stacsDBPWD = pro.getProperty("uat.STACS.DB.password");
            stacsDBURLr = pro.getProperty("uat.STACS.DB.url");
            RB_SystemAdmin_UN = pro.getProperty("uat.sysadmin.username");
            RB_SystemAdmin_Pwd = pro.getProperty("uat.sysadmin.password");
            SuperUserSSO_UN = pro.getProperty("uat.SuperUserSSO_UN.username");
            SuperUserSSO_PW = pro.getProperty("uat.SuperUserSSO_PW.password");
            UW4userName = pro.getProperty("qa.UW4username");
            UW4passWord = pro.getProperty("qa.UW4password");
//            dynamicdatafoldersharedpath = pro.getProperty("uat.e2e.dynamicdatafoldersharedpath");
            dynamicdatafoldersharedpathCV = pro.getProperty("uat.e2e.dynamicdatafoldersharedpathCV");
            dynamicdatafoldersharedpathQS = pro.getProperty("uat.e2e.q2s.dynamicdatafoldersharedpath");
            dynamicdatafoldersharedpathSB = pro.getProperty("uat.e2e.s2b.dynamicdatafoldersharedpath");
        } else if (ENV.trim().equalsIgnoreCase("stage")) {
            URL = pro.getProperty("stage.url");
            userName = pro.getProperty("stage.username");
            passWord = pro.getProperty("stage.password");
            UW1_UserName = pro.getProperty("stage.uw1.username");
            UW1_Pwd = pro.getProperty("stage.uw1.password");
            UW2_UserName = pro.getProperty("stage.uw2.username");
            UW2_Pwd = pro.getProperty("stage.uw2.password");
        } else if (ENV.trim().equalsIgnoreCase("preprod")) {
            DATA_TABLE_FILE_PATH = base.Config.DATATABLE_ROOT_PATH + DATA_TABLE_FILE_NAME_PREPROD;
            System.out.println("preprod Data table path: " + DATA_TABLE_FILE_PATH);
            base.Config.DATATABLE_FILE_PATH = DATA_TABLE_FILE_PATH;
            URL = pro.getProperty("preprod.url");
            userName = pro.getProperty("preprod.username");
            passWord = pro.getProperty("preprod.password");
            SSOSuperuserName = pro.getProperty("preprod.ssoSuperusername");
            SSOpassWord = pro.getProperty("preprod.ssopassword");
            UW1_UserName = pro.getProperty("qa.uw1.username");
            UW1_Pwd = pro.getProperty("qa.uw1.password");
            UW2_UserName = pro.getProperty("qa.uw2.username");
            UW2_Pwd = pro.getProperty("qa.uw2.password");
            PSAuserName = pro.getProperty("qa.PSAusername");
            PSApassWord = pro.getProperty("qa.PSApassword");
            UW4userName = pro.getProperty("qa.UW4username");
            UW4passWord = pro.getProperty("qa.UW4password");
            UWpassword = pro.getProperty("qa.UWpassword");
            RB_PreSales_UN = pro.getProperty("qa.presalsebasic.username");
            RB_PreSales_Pwd = pro.getProperty("qa.presalsebasic.password");
            RB_SalesRepIndividual_UN = pro.getProperty("qa.salesrepindividual.username");
            RB_SalesRepIndividual_Pwd = pro.getProperty("qa.salesrepindividual.password");
            RB_Underwriting1_UN = pro.getProperty("qa.Underwriting1.username");
            RB_Underwriting1_Pwd = pro.getProperty("qa.Underwriting1.password");
            RB_SystemAdmin_UN = pro.getProperty("qa.sysadmin.username");
            RB_SystemAdmin_Pwd = pro.getProperty("qa.sysadmin.password");
            RB_SuperUser_UN = pro.getProperty("qa.superuser.username");
            RB_SuperUser_Pwd = pro.getProperty("qa.superuser.password");
            RB_SalesRepRSO_UN = pro.getProperty("qa.salesreprso.username");
            RB_SalesRepRSO_Pwd = pro.getProperty("qa.salesreprso.password");
            RB_SalesRepRegion_UN = pro.getProperty("qa.salesrepsalesrepregion.username");
            RB_SalesRepRegion_Pwd = pro.getProperty("qa.salesrepsalesrepregion.password");
            RB_SalesRepGlobal_UN = pro.getProperty("qa.SalesRepGlobal.username");
            RB_SalesRepGlobal_Pwd = pro.getProperty("qa.SalesRepGlobal.password");
            rslsfURL = pro.getProperty("preprod.rslsf.url");
            rslsfUN = pro.getProperty("preprod.rslsf.username");
            rslsfPWD = pro.getProperty("preprod.rslsf.password");
            easURL = pro.getProperty("preprod.eas.url");
            easUN = pro.getProperty("preprod.eas.username");
            easPWD = pro.getProperty("preprod.eas.password");
            pacsDBDriver = pro.getProperty("preprod.PACS.DB.driver");
            pacsDBUN = pro.getProperty("preprod.PACS.DB.username");
            pacsDBPWD = pro.getProperty("preprod.PACS.DB.password");
            pacsDBURLr = pro.getProperty("preprod.PACS.DB.url");
            apsDBDriver = pro.getProperty("preprod.APS.DB.driver");
            apsDBUN = pro.getProperty("preprod.APS.DB.username");
            apsDBPWD = pro.getProperty("preprod.APS.DB.password");
            apsDBURLr = pro.getProperty("preprod.APS.DB.url");
            vueDBDriver = pro.getProperty("preprod.VUE.DB.driver");
            vueDBUN = pro.getProperty("preprod.VUE.DB.username");
            vueDBPWD = pro.getProperty("preprod.VUE.DB.password");
            vueDBURLr = pro.getProperty("preprod.VUE.DB.url");
            stacsinterimDBDriver = pro.getProperty("preprod.STACSINTERIM.DB.driver");
            stacsinterimDBUN = pro.getProperty("preprod.STACSINTERIM.DB.username");
            stacsinterimDBPWD = pro.getProperty("preprod.STACSINTERIM.DB.password");
            stacsinterimDBURLr = pro.getProperty("preprod.STACSINTERIM.DB.url");
            stacsDBDriver = pro.getProperty("preprod.STACS.DB.driver");
            stacsDBUN = pro.getProperty("preprod.STACS.DB.username");
            stacsDBPWD = pro.getProperty("preprod.STACS.DB.password");
            stacsDBURLr = pro.getProperty("preprod.STACS.DB.url");
//            dynamicdatafoldersharedpath = pro.getProperty("dev.e2e.dynamicdatafoldersharedpath");
            dynamicdatafoldersharedpathCV = pro.getProperty("dev.e2e.dynamicdatafoldersharedpathCV");
            dynamicdatafoldersharedpathCV = pro.getProperty("preprod.e2e.dynamicdatafoldersharedpathCV");
            dynamicdatafoldersharedpathQS = pro.getProperty("preprod.e2e.q2s.dynamicdatafoldersharedpath");
            dynamicdatafoldersharedpathSB = pro.getProperty("preprod.e2e.s2b.dynamicdatafoldersharedpath");
        } else if (ENV.trim().equalsIgnoreCase("preprodphase1")) {
            DATA_TABLE_FILE_PATH = base.Config.DATATABLE_ROOT_PATH + DATA_TABLE_FILE_NAME_PREPROD;
            System.out.println("preprod Data table path: " + DATA_TABLE_FILE_PATH);
            base.Config.DATATABLE_FILE_PATH = DATA_TABLE_FILE_PATH;
            URL = pro.getProperty("preprodphase1.url");
            userName = pro.getProperty("preprodphase1.username");
            passWord = pro.getProperty("preprodphase1.password");
            UW1_UserName = pro.getProperty("qa.uw1.username");
            UW1_Pwd = pro.getProperty("qa.uw1.password");
            UW2_UserName = pro.getProperty("qa.uw2.username");
            UW2_Pwd = pro.getProperty("qa.uw2.password");
            RB_PreSales_UN = pro.getProperty("qa.presalsebasic.username");
            RB_PreSales_Pwd = pro.getProperty("qa.presalsebasic.password");
            RB_SalesRepIndividual_UN = pro.getProperty("qa.salesrepindividual.username");
            RB_SalesRepIndividual_Pwd = pro.getProperty("qa.salesrepindividual.password");
            RB_Underwriting1_UN = pro.getProperty("qa.Underwriting1.username");
            RB_Underwriting1_Pwd = pro.getProperty("qa.Underwriting1.password");
            RB_SystemAdmin_UN = pro.getProperty("qa.sysadmin.username");
            RB_SystemAdmin_Pwd = pro.getProperty("qa.sysadmin.password");
            RB_SuperUser_UN = pro.getProperty("qa.superuser.username");
            RB_SuperUser_Pwd = pro.getProperty("qa.superuser.password");
            RB_SalesRepRSO_UN = pro.getProperty("qa.salesreprso.username");
            RB_SalesRepRSO_Pwd = pro.getProperty("qa.salesreprso.password");
            RB_SalesRepRegion_UN = pro.getProperty("qa.salesrepsalesrepregion.username");
            RB_SalesRepRegion_Pwd = pro.getProperty("qa.salesrepsalesrepregion.password");
            RB_SalesRepGlobal_UN = pro.getProperty("qa.SalesRepGlobal.username");
            RB_SalesRepGlobal_Pwd = pro.getProperty("qa.SalesRepGlobal.password");
            rslsfURL = pro.getProperty("preprod.rslsf.url");
            rslsfUN = pro.getProperty("preprod.rslsf.username");
            rslsfPWD = pro.getProperty("preprod.rslsf.password");
            easURL = pro.getProperty("preprod.eas.url");
            easUN = pro.getProperty("preprod.eas.username");
            easPWD = pro.getProperty("preprod.eas.password");
            pacsDBDriver = pro.getProperty("preprod.PACS.DB.driver");
            pacsDBUN = pro.getProperty("preprod.PACS.DB.username");
            pacsDBPWD = pro.getProperty("preprod.PACS.DB.password");
            pacsDBURLr = pro.getProperty("preprod.PACS.DB.url");
            apsDBDriver = pro.getProperty("preprod.APS.DB.driver");
            apsDBUN = pro.getProperty("preprod.APS.DB.username");
            apsDBPWD = pro.getProperty("preprod.APS.DB.password");
            apsDBURLr = pro.getProperty("preprod.APS.DB.url");
            vueDBDriver = pro.getProperty("preprod.VUE.DB.driver");
            vueDBUN = pro.getProperty("preprod.VUE.DB.username");
            vueDBPWD = pro.getProperty("preprod.VUE.DB.password");
            vueDBURLr = pro.getProperty("preprod.VUE.DB.url");
            stacsinterimDBDriver = pro.getProperty("preprod.STACSINTERIM.DB.driver");
            stacsinterimDBUN = pro.getProperty("preprod.STACSINTERIM.DB.username");
            stacsinterimDBPWD = pro.getProperty("preprod.STACSINTERIM.DB.password");
            stacsinterimDBURLr = pro.getProperty("preprod.STACSINTERIM.DB.url");
            stacsDBDriver = pro.getProperty("preprod.STACS.DB.driver");
            stacsDBUN = pro.getProperty("preprod.STACS.DB.username");
            stacsDBPWD = pro.getProperty("preprod.STACS.DB.password");
            stacsDBURLr = pro.getProperty("preprod.STACS.DB.url");
//            dynamicdatafoldersharedpath = pro.getProperty("dev.e2e.dynamicdatafoldersharedpath");
            dynamicdatafoldersharedpathCV = pro.getProperty("dev.e2e.dynamicdatafoldersharedpathCV");
            dynamicdatafoldersharedpathCV = pro.getProperty("preprod.e2e.dynamicdatafoldersharedpathCV");
            dynamicdatafoldersharedpathQS = pro.getProperty("preprod.e2e.q2s.dynamicdatafoldersharedpath");
            dynamicdatafoldersharedpathSB = pro.getProperty("preprod.e2e.s2b.dynamicdatafoldersharedpath");
        } else if (ENV.trim().equalsIgnoreCase("STDQA")) {
            DATA_TABLE_FILE_PATH = base.Config.DATATABLE_ROOT_PATH + DATA_TABLE_FILE_NAME_QA;
            System.out.println("qa Data table path: " + DATA_TABLE_FILE_PATH);
            base.Config.DATATABLE_FILE_PATH = DATA_TABLE_FILE_PATH;
            URL = pro.getProperty("qa.url");
            userName = pro.getProperty("qa.username");
            passWord = pro.getProperty("qa.password");
            UW1_UserName = pro.getProperty("qa.uw1.username");
            UW1_Pwd = pro.getProperty("qa.uw1.password");
            UW2_UserName = pro.getProperty("qa.uw2.username");
            UW2_Pwd = pro.getProperty("qa.uw2.password");
            RB_PreSales_UN = pro.getProperty("qa.presalsebasic.username");
            RB_PreSales_Pwd = pro.getProperty("qa.presalsebasic.password");
            RB_SalesRepIndividual_UN = pro.getProperty("qa.salesrepindividual.username");
            RB_SalesRepIndividual_Pwd = pro.getProperty("qa.salesrepindividual.password");
            RB_Underwriting1_UN = pro.getProperty("qa.Underwriting1.username");
            RB_Underwriting1_Pwd = pro.getProperty("qa.Underwriting1.password");
            RB_SystemAdmin_UN = pro.getProperty("qa.sysadmin.username");
            RB_SystemAdmin_Pwd = pro.getProperty("qa.sysadmin.password");
            RB_SuperUser_UN = pro.getProperty("qa.superuser.username");
            RB_SuperUser_Pwd = pro.getProperty("qa.superuser.password");
            RB_SalesRepRSO_UN = pro.getProperty("qa.salesreprso.username");
            RB_SalesRepRSO_Pwd = pro.getProperty("qa.salesreprso.password");
            RB_SalesRepRegion_UN = pro.getProperty("qa.salesrepsalesrepregion.username");
            RB_SalesRepRegion_Pwd = pro.getProperty("qa.salesrepsalesrepregion.password");
            RB_SalesRepGlobal_UN = pro.getProperty("qa.SalesRepGlobal.username");
            RB_SalesRepGlobal_Pwd = pro.getProperty("qa.SalesRepGlobal.password");
            rslsfURL = pro.getProperty("qa.rslsf.url");
            rslsfUN = pro.getProperty("qa.rslsf.username");
            rslsfPWD = pro.getProperty("qa.rslsf.password");
            easURL = pro.getProperty("qa.eas.url");
            easUN = pro.getProperty("qa.eas.username");
            easPWD = pro.getProperty("qa.eas.password");
            pacsDBDriver = pro.getProperty("qa.PACS.DB.driver");
            pacsDBUN = pro.getProperty("qa.PACS.DB.username");
            pacsDBPWD = pro.getProperty("qa.PACS.DB.password");
            pacsDBURLr = pro.getProperty("qa.PACS.DB.url");
            apsDBDriver = pro.getProperty("qa.APS.DB.driver");
            apsDBUN = pro.getProperty("qa.APS.DB.username");
            apsDBPWD = pro.getProperty("qa.APS.DB.password");
            apsDBURLr = pro.getProperty("qa.APS.DB.url");
            vueDBDriver = pro.getProperty("qa.VUE.DB.driver");
            vueDBUN = pro.getProperty("qa.VUE.DB.username");
            vueDBPWD = pro.getProperty("qa.VUE.DB.password");
            vueDBURLr = pro.getProperty("qa.VUE.DB.url");
            stacsinterimDBDriver = pro.getProperty("qa.STACSINTERIM.DB.driver");
            stacsinterimDBUN = pro.getProperty("qa.STACSINTERIM.DB.username");
            stacsinterimDBPWD = pro.getProperty("qa.STACSINTERIM.DB.password");
            stacsinterimDBURLr = pro.getProperty("qa.STACSINTERIM.DB.url");
            stacsDBDriver = pro.getProperty("qa.STACS.DB.driver");
            stacsDBUN = pro.getProperty("qa.STACS.DB.username");
            stacsDBPWD = pro.getProperty("qa.STACS.DB.password");
            stacsDBURLr = pro.getProperty("qa.STACS.DB.url");
            eisDBDriver = pro.getProperty("EIS.DB.driver");
            eisDBUN = pro.getProperty("EIS.DB.username");
            eisDBPWD = pro.getProperty("EIS.DB.password");
            eisDBURLr = pro.getProperty("EIS.DB.url");
//            dynamicdatafoldersharedpath = pro.getProperty("qa.e2e.dynamicdatafoldersharedpath");
            dynamicdatafoldersharedpathCV = pro.getProperty("qa.e2e.dynamicdatafoldersharedpathCV");
            dynamicdatafoldersharedpathQS = pro.getProperty("qa.e2e.q2s.dynamicdatafoldersharedpath");
            dynamicdatafoldersharedpathSB = pro.getProperty("qa.e2e.s2b.dynamicdatafoldersharedpath");

        /*else if (ENV.trim().equalsIgnoreCase("rsosf")) {
            URL = pro.getProperty("rsosf.url");
            userName = pro.getProperty("rsosf.username");
            passWord = pro.getProperty("rsosf.password");
        } else if (ENV.trim().equalsIgnoreCase("eas")) {
            URL = pro.getProperty("eas.url");
            userName = pro.getProperty("eas.username");
            passWord = pro.getProperty("eas.password");
        }*/
        } else if (ENV.trim().equalsIgnoreCase("EISQA")) {
            DATA_TABLE_FILE_PATH = base.Config.DATATABLE_ROOT_PATH + DATA_TABLE_FILE_NAME_QA;
            System.out.println("qa Data table path: " + DATA_TABLE_FILE_PATH);
            base.Config.DATATABLE_FILE_PATH = DATA_TABLE_FILE_PATH;
            URL = pro.getProperty("eis.qa.url");
            userName = pro.getProperty("eis.qa.username");
            passWord = pro.getProperty("eis.qa.password");
            UW1_UserName = pro.getProperty("qa.uw1.username");
            UW1_Pwd = pro.getProperty("qa.uw1.password");
            UW2_UserName = pro.getProperty("qa.uw2.username");
            UW2_Pwd = pro.getProperty("qa.uw2.password");
            RB_PreSales_UN = pro.getProperty("qa.presalsebasic.username");
            RB_PreSales_Pwd = pro.getProperty("qa.presalsebasic.password");
            RB_SalesRepIndividual_UN = pro.getProperty("qa.salesrepindividual.username");
            RB_SalesRepIndividual_Pwd = pro.getProperty("qa.salesrepindividual.password");
            RB_Underwriting1_UN = pro.getProperty("qa.Underwriting1.username");
            RB_Underwriting1_Pwd = pro.getProperty("qa.Underwriting1.password");
            RB_SystemAdmin_UN = pro.getProperty("qa.sysadmin.username");
            RB_SystemAdmin_Pwd = pro.getProperty("qa.sysadmin.password");
            RB_SuperUser_UN = pro.getProperty("qa.superuser.username");
            RB_SuperUser_Pwd = pro.getProperty("qa.superuser.password");
            RB_SalesRepRSO_UN = pro.getProperty("qa.salesreprso.username");
            RB_SalesRepRSO_Pwd = pro.getProperty("qa.salesreprso.password");
            RB_SalesRepRegion_UN = pro.getProperty("qa.salesrepsalesrepregion.username");
            RB_SalesRepRegion_Pwd = pro.getProperty("qa.salesrepsalesrepregion.password");
            RB_SalesRepGlobal_UN = pro.getProperty("qa.SalesRepGlobal.username");
            RB_SalesRepGlobal_Pwd = pro.getProperty("qa.SalesRepGlobal.password");
            rslsfURL = pro.getProperty("qa.rslsf.url");
            rslsfUN = pro.getProperty("qa.rslsf.username");
            rslsfPWD = pro.getProperty("qa.rslsf.password");
            easURL = pro.getProperty("qa.eas.url");
            easUN = pro.getProperty("qa.eas.username");
            easPWD = pro.getProperty("qa.eas.password");
            pacsDBDriver = pro.getProperty("qa.PACS.DB.driver");
            pacsDBUN = pro.getProperty("qa.PACS.DB.username");
            pacsDBPWD = pro.getProperty("qa.PACS.DB.password");
            pacsDBURLr = pro.getProperty("qa.PACS.DB.url");
            apsDBDriver = pro.getProperty("qa.APS.DB.driver");
            apsDBUN = pro.getProperty("qa.APS.DB.username");
            apsDBPWD = pro.getProperty("qa.APS.DB.password");
            apsDBURLr = pro.getProperty("qa.APS.DB.url");
            vueDBDriver = pro.getProperty("qa.VUE.DB.driver");
            vueDBUN = pro.getProperty("qa.VUE.DB.username");
            vueDBPWD = pro.getProperty("qa.VUE.DB.password");
            vueDBURLr = pro.getProperty("qa.VUE.DB.url");
            stacsinterimDBDriver = pro.getProperty("qa.STACSINTERIM.DB.driver");
            stacsinterimDBUN = pro.getProperty("qa.STACSINTERIM.DB.username");
            stacsinterimDBPWD = pro.getProperty("qa.STACSINTERIM.DB.password");
            stacsinterimDBURLr = pro.getProperty("qa.STACSINTERIM.DB.url");
            stacsDBDriver = pro.getProperty("qa.STACS.DB.driver");
            stacsDBUN = pro.getProperty("qa.STACS.DB.username");
            stacsDBPWD = pro.getProperty("qa.STACS.DB.password");
            stacsDBURLr = pro.getProperty("qa.STACS.DB.url");
            eisDBDriver = pro.getProperty("EIS.DB.driver");
            eisDBUN = pro.getProperty("EIS.DB.username");
            eisDBPWD = pro.getProperty("EIS.DB.password");
            eisDBURLr = pro.getProperty("EIS.DB.url");
            dynamicdatafoldersharedpathCV = pro.getProperty("qa.e2e.dynamicdatafoldersharedpathCV");
            dynamicdatafoldersharedpathQS = pro.getProperty("qa.e2e.q2s.dynamicdatafoldersharedpath");
            dynamicdatafoldersharedpathSB = pro.getProperty("qa.e2e.s2b.dynamicdatafoldersharedpath");
        } else if (ENV.trim().equalsIgnoreCase("migration")) {
            DATA_TABLE_FILE_PATH = base.Config.DATATABLE_ROOT_PATH + DATA_TABLE_FILE_NAME_QA;
            System.out.println("qa Data table path: " + DATA_TABLE_FILE_PATH);
            base.Config.DATATABLE_FILE_PATH = DATA_TABLE_FILE_PATH;
            URL = pro.getProperty("migration.url");
            userName = pro.getProperty("qa.username");
            passWord = pro.getProperty("qa.password");
            SSOSuperuserName = pro.getProperty("qa.ssoSuperusername");
            SSOAdminuserName = pro.getProperty("qa.ssoAdminusername");
            SSOpassWord = pro.getProperty("qa.ssopassword");
            UW1_UserName = pro.getProperty("qa.uw1.username");
            UW1_Pwd = pro.getProperty("qa.uw1.password");
            UW2_UserName = pro.getProperty("qa.uw2.username");
            UW2_Pwd = pro.getProperty("qa.uw2.password");
            RB_PreSales_UN = pro.getProperty("qa.presalsebasic.username");
            RB_PreSales_Pwd = pro.getProperty("qa.presalsebasic.password");
            RB_SalesRepIndividual_UN = pro.getProperty("qa.salesrepindividual.username");
            RB_SalesRepIndividual_Pwd = pro.getProperty("qa.salesrepindividual.password");
            RB_Underwriting1_UN = pro.getProperty("qa.Underwriting1.username");
            RB_Underwriting1_Pwd = pro.getProperty("qa.Underwriting1.password");
            RB_SystemAdmin_UN = pro.getProperty("qa.sysadmin.username");
            RB_SystemAdmin_Pwd = pro.getProperty("qa.sysadmin.password");
            RB_SuperUser_UN = pro.getProperty("qa.superuser.username");
            RB_SuperUser_Pwd = pro.getProperty("qa.superuser.password");
            RB_SalesRepRSO_UN = pro.getProperty("qa.salesreprso.username");
            RB_SalesRepRSO_Pwd = pro.getProperty("qa.salesreprso.password");
            RB_SalesRepRegion_UN = pro.getProperty("qa.salesrepsalesrepregion.username");
            RB_SalesRepRegion_Pwd = pro.getProperty("qa.salesrepsalesrepregion.password");
            RB_SalesRepGlobal_UN = pro.getProperty("qa.SalesRepGlobal.username");
            RB_SalesRepGlobal_Pwd = pro.getProperty("qa.SalesRepGlobal.password");
            rslsfURL = pro.getProperty("qa.rslsf.url");
            rslsfUN = pro.getProperty("qa.rslsf.username");
            rslsfPWD = pro.getProperty("qa.rslsf.password");
            easURL = pro.getProperty("qa.eas.url");
            easUN = pro.getProperty("qa.eas.username");
            easPWD = pro.getProperty("eis.qa.password");
            pacsDBDriver = pro.getProperty("qa.PACS.DB.driver");
            pacsDBUN = pro.getProperty("qa.PACS.DB.username");
            pacsDBPWD = pro.getProperty("qa.PACS.DB.password");
            pacsDBURLr = pro.getProperty("qa.PACS.DB.url");
            apsDBDriver = pro.getProperty("qa.APS.DB.driver");
            apsDBUN = pro.getProperty("qa.APS.DB.username");
            apsDBPWD = pro.getProperty("qa.APS.DB.password");
            apsDBURLr = pro.getProperty("qa.APS.DB.url");
            vueDBDriver = pro.getProperty("qa.VUE.DB.driver");
            vueDBUN = pro.getProperty("qa.VUE.DB.username");
            vueDBPWD = pro.getProperty("qa.VUE.DB.password");
            vueDBURLr = pro.getProperty("qa.VUE.DB.url");
            stacsinterimDBDriver = pro.getProperty("qa.STACSINTERIM.DB.driver");
            stacsinterimDBUN = pro.getProperty("qa.STACSINTERIM.DB.username");
            stacsinterimDBPWD = pro.getProperty("qa.STACSINTERIM.DB.password");
            stacsinterimDBURLr = pro.getProperty("qa.STACSINTERIM.DB.url");
            stacsDBDriver = pro.getProperty("qa.STACS.DB.driver");
            stacsDBUN = pro.getProperty("qa.STACS.DB.username");
            stacsDBPWD = pro.getProperty("qa.STACS.DB.password");
            stacsDBURLr = pro.getProperty("qa.STACS.DB.url");
            eisDBDriver = pro.getProperty("EIS.DB.driver");
            eisDBUN = pro.getProperty("EIS.DB.username");
            eisDBPWD = pro.getProperty("EIS.DB.password");
            eisDBURLr = pro.getProperty("EIS.DB.url");
//            dynamicdatafoldersharedpath = pro.getProperty("qa.e2e.dynamicdatafoldersharedpath");
            dynamicdatafoldersharedpathCV = pro.getProperty("qa.e2e.dynamicdatafoldersharedpathCV");
            dynamicdatafoldersharedpathQS = pro.getProperty("qa.e2e.q2s.dynamicdatafoldersharedpath");
            dynamicdatafoldersharedpathSB = pro.getProperty("qa.e2e.s2b.dynamicdatafoldersharedpath");
        } else if (ENV.trim().equalsIgnoreCase("mqa")) {
            DATA_TABLE_FILE_PATH = base.Config.DATATABLE_ROOT_PATH + DATA_TABLE_FILE_NAME_QA;
            System.out.println("qa Data table path: " + DATA_TABLE_FILE_PATH);
            base.Config.DATATABLE_FILE_PATH = DATA_TABLE_FILE_PATH;
            URL = pro.getProperty("mqa.url");
            userName = pro.getProperty("qa.username");
            passWord = pro.getProperty("qa.password");
            PreSaluserName = pro.getProperty("qa.PreSaleurname");
            PreSalpassWord = pro.getProperty("qa.PreSalepassword");
            PSAuserName = pro.getProperty("qa.PSAusername");
            PSApassWord = pro.getProperty("qa.PSApassword");
            UW4userName = pro.getProperty("qa.UW4username");
            UW3userName = pro.getProperty("qa.UW3username");
            UW2userName = pro.getProperty("qa.UW2username");
            UW1userName = pro.getProperty("qa.UW1username");
            UnderwritingName = pro.getProperty("qa.UnderwritingName");
            UWTraineeuserName = pro.getProperty("qa.UWTraineeusername");
            UWAuserName = pro.getProperty("qa.UWAssistantusername");
            UWpassword = pro.getProperty("qa.UWpassword");
            ConservationAnalystuserName = pro.getProperty("qa.ConservationAnalystusernam");
            ConservationAnalystpassWord = pro.getProperty("qa.ConservationAnalystpassword");
            SSOAdminuserName = pro.getProperty("qa.ssoAdminusername");
            UW1_UserName = pro.getProperty("qa.uw1.username");
            UW1_Pwd = pro.getProperty("qa.uw1.password");
            UW2_UserName = pro.getProperty("qa.uw2.username");
            UW2_Pwd = pro.getProperty("qa.uw2.password");
            SSOSuperuserName = pro.getProperty("qa.ssoSuperusername");
            SSOpassWord = pro.getProperty("qa.ssopassword");
            RB_PreSales_UN = pro.getProperty("qa.presalsebasic.username");
            RB_PreSales_Pwd = pro.getProperty("qa.presalsebasic.password");
            RB_SalesRepIndividual_UN = pro.getProperty("qa.salesrepindividual.username");
            RB_SalesRepIndividual_Pwd = pro.getProperty("qa.salesrepindividual.password");
            RB_Underwriting1_UN = pro.getProperty("qa.Underwriting1.username");
            RB_Underwriting1_Pwd = pro.getProperty("qa.Underwriting1.password");
            RB_SystemAdmin_UN = pro.getProperty("qa.sysadmin.username");
            RB_SystemAdmin_Pwd = pro.getProperty("qa.sysadmin.password");
            RB_SuperUser_UN = pro.getProperty("qa.superuser.username");
            RB_SuperUser_Pwd = pro.getProperty("qa.superuser.password");
            RB_SalesRepRSO_UN = pro.getProperty("qa.salesreprso.username");
            RB_SalesRepRSO_Pwd = pro.getProperty("qa.salesreprso.password");
            RB_SalesRepRegion_UN = pro.getProperty("qa.salesrepsalesrepregion.username");
            RB_SalesRepRegion_Pwd = pro.getProperty("qa.salesrepsalesrepregion.password");
            RB_SalesRepGlobal_UN = pro.getProperty("qa.SalesRepGlobal.username");
            RB_SalesRepGlobal_Pwd = pro.getProperty("qa.SalesRepGlobal.password");
            SuperUserSSO_UN = pro.getProperty("qa.SuperUserSSO_UN.username");
            SuperUserSSO_PW = pro.getProperty("qa.SuperUserSSO_PW.password");
            rslsfURL = pro.getProperty("qa.rslsf.url");
            rslsfUN = pro.getProperty("qa.rslsf.username");
            rslsfPWD = pro.getProperty("qa.rslsf.password");
            easURL = pro.getProperty("qa.eas.url");
            easUN = pro.getProperty("qa.eas.username");
            easPWD = pro.getProperty("qa.eas.password");
            pacsDBDriver = pro.getProperty("qa.PACS.DB.driver");
            pacsDBUN = pro.getProperty("qa.PACS.DB.username");
            pacsDBPWD = pro.getProperty("qa.PACS.DB.password");
            pacsDBURLr = pro.getProperty("qa.PACS.DB.url");
            apsDBDriver = pro.getProperty("qa.APS.DB.driver");
            apsDBUN = pro.getProperty("qa.APS.DB.username");
            apsDBPWD = pro.getProperty("qa.APS.DB.password");
            apsDBURLr = pro.getProperty("qa.APS.DB.url");
            vueDBDriver = pro.getProperty("qa.VUE.DB.driver");
            vueDBUN = pro.getProperty("qa.VUE.DB.username");
            vueDBPWD = pro.getProperty("qa.VUE.DB.password");
            vueDBURLr = pro.getProperty("qa.VUE.DB.url");
            stacsinterimDBDriver = pro.getProperty("qa.STACSINTERIM.DB.driver");
            stacsinterimDBUN = pro.getProperty("qa.STACSINTERIM.DB.username");
            stacsinterimDBPWD = pro.getProperty("qa.STACSINTERIM.DB.password");
            stacsinterimDBURLr = pro.getProperty("qa.STACSINTERIM.DB.url");
            stacsDBDriver = pro.getProperty("qa.STACS.DB.driver");
            stacsDBUN = pro.getProperty("qa.STACS.DB.username");
            stacsDBPWD = pro.getProperty("qa.STACS.DB.password");
            stacsDBURLr = pro.getProperty("qa.STACS.DB.url");
            eisDBDriver = pro.getProperty("EIS.DB.driver");
            eisDBUN = pro.getProperty("EIS.DB.username");
            eisDBPWD = pro.getProperty("EIS.DB.password");
            eisDBURLr = pro.getProperty("EIS.DB.url");
//            dynamicdatafoldersharedpath = pro.getProperty("qa.e2e.dynamicdatafoldersharedpath");
            dynamicdatafoldersharedpathCV = pro.getProperty("qa.e2e.dynamicdatafoldersharedpathCV");
            dynamicdatafoldersharedpathQS = pro.getProperty("qa.e2e.q2s.dynamicdatafoldersharedpath");
            dynamicdatafoldersharedpathSB = pro.getProperty("qa.e2e.s2b.dynamicdatafoldersharedpath");
        } else if (ENV.trim().equalsIgnoreCase("sit")) {
            DATA_TABLE_FILE_PATH = base.Config.DATATABLE_ROOT_PATH + DATA_TABLE_FILE_NAME_QA;
            System.out.println("qa Data table path: " + DATA_TABLE_FILE_PATH);
            base.Config.DATATABLE_FILE_PATH = DATA_TABLE_FILE_PATH;
            URL = pro.getProperty("dev.url");
            userName = pro.getProperty("dev.username");
            passWord = pro.getProperty("dev.password");
            PreSaluserName = pro.getProperty("qa.PreSaleurname");
            PreSalpassWord = pro.getProperty("qa.PreSalepassword");
            PSAuserName = pro.getProperty("qa.PSAusername");
            PSApassWord = pro.getProperty("qa.PSApassword");
            UW4userName = pro.getProperty("qa.UW4username");
            UW3userName = pro.getProperty("qa.UW3username");
            UW2userName = pro.getProperty("qa.UW2username");
            UW1userName = pro.getProperty("qa.UW1username");
            UnderwritingName = pro.getProperty("qa.UnderwritingName");
            UWTraineeuserName = pro.getProperty("qa.UWTraineeusername");
            UWAuserName = pro.getProperty("qa.UWAssistantusername");
            UWpassword = pro.getProperty("qa.UWpassword");
            ConservationAnalystuserName = pro.getProperty("qa.ConservationAnalystusernam");
            ConservationAnalystpassWord = pro.getProperty("qa.ConservationAnalystpassword");
            SSOAdminuserName = pro.getProperty("qa.ssoAdminusername");
            UW1_UserName = pro.getProperty("qa.uw1.username");
            UW1_Pwd = pro.getProperty("qa.uw1.password");
            UW2_UserName = pro.getProperty("qa.uw2.username");
            UW2_Pwd = pro.getProperty("qa.uw2.password");
            SSOSuperuserName = pro.getProperty("qa.ssoSuperusername");
            SSOpassWord = pro.getProperty("qa.ssopassword");
            RB_PreSales_UN = pro.getProperty("qa.presalsebasic.username");
            RB_PreSales_Pwd = pro.getProperty("qa.presalsebasic.password");
            RB_SalesRepIndividual_UN = pro.getProperty("qa.salesrepindividual.username");
            RB_SalesRepIndividual_Pwd = pro.getProperty("qa.salesrepindividual.password");
            RB_Underwriting1_UN = pro.getProperty("qa.Underwriting1.username");
            RB_Underwriting1_Pwd = pro.getProperty("qa.Underwriting1.password");
            RB_SystemAdmin_UN = pro.getProperty("qa.sysadmin.username");
            RB_SystemAdmin_Pwd = pro.getProperty("qa.sysadmin.password");
            RB_SuperUser_UN = pro.getProperty("qa.superuser.username");
            RB_SuperUser_Pwd = pro.getProperty("qa.superuser.password");
            RB_SalesRepRSO_UN = pro.getProperty("qa.salesreprso.username");
            RB_SalesRepRSO_Pwd = pro.getProperty("qa.salesreprso.password");
            RB_SalesRepRegion_UN = pro.getProperty("qa.salesrepsalesrepregion.username");
            RB_SalesRepRegion_Pwd = pro.getProperty("qa.salesrepsalesrepregion.password");
            RB_SalesRepGlobal_UN = pro.getProperty("qa.SalesRepGlobal.username");
            RB_SalesRepGlobal_Pwd = pro.getProperty("qa.SalesRepGlobal.password");
            SuperUserSSO_UN = pro.getProperty("qa.SuperUserSSO_UN.username");
            SuperUserSSO_PW = pro.getProperty("qa.SuperUserSSO_PW.password");
            rslsfURL = pro.getProperty("qa.rslsf.url");
            rslsfUN = pro.getProperty("qa.rslsf.username");
            rslsfPWD = pro.getProperty("qa.rslsf.password");
            easURL = pro.getProperty("qa.eas.url");
            easUN = pro.getProperty("qa.eas.username");
            easPWD = pro.getProperty("qa.eas.password");
            pacsDBDriver = pro.getProperty("qa.PACS.DB.driver");
            pacsDBUN = pro.getProperty("qa.PACS.DB.username");
            pacsDBPWD = pro.getProperty("qa.PACS.DB.password");
            pacsDBURLr = pro.getProperty("qa.PACS.DB.url");
            apsDBDriver = pro.getProperty("qa.APS.DB.driver");
            apsDBUN = pro.getProperty("qa.APS.DB.username");
            apsDBPWD = pro.getProperty("qa.APS.DB.password");
            apsDBURLr = pro.getProperty("qa.APS.DB.url");
            vueDBDriver = pro.getProperty("qa.VUE.DB.driver");
            vueDBUN = pro.getProperty("qa.VUE.DB.username");
            vueDBPWD = pro.getProperty("qa.VUE.DB.password");
            vueDBURLr = pro.getProperty("qa.VUE.DB.url");
            stacsinterimDBDriver = pro.getProperty("qa.STACSINTERIM.DB.driver");
            stacsinterimDBUN = pro.getProperty("qa.STACSINTERIM.DB.username");
            stacsinterimDBPWD = pro.getProperty("qa.STACSINTERIM.DB.password");
            stacsinterimDBURLr = pro.getProperty("qa.STACSINTERIM.DB.url");
            stacsDBDriver = pro.getProperty("qa.STACS.DB.driver");
            stacsDBUN = pro.getProperty("qa.STACS.DB.username");
            stacsDBPWD = pro.getProperty("qa.STACS.DB.password");
            stacsDBURLr = pro.getProperty("qa.STACS.DB.url");
            eisDBDriver = pro.getProperty("EIS.DB.driver");
            eisDBUN = pro.getProperty("EIS.DB.username");
            eisDBPWD = pro.getProperty("EIS.DB.password");
            eisDBURLr = pro.getProperty("EIS.DB.url");
//            dynamicdatafoldersharedpath = pro.getProperty("qa.e2e.dynamicdatafoldersharedpath");
            dynamicdatafoldersharedpathCV = pro.getProperty("qa.e2e.dynamicdatafoldersharedpathCV");
            dynamicdatafoldersharedpathQS = pro.getProperty("qa.e2e.q2s.dynamicdatafoldersharedpath");
            dynamicdatafoldersharedpathSB = pro.getProperty("qa.e2e.s2b.dynamicdatafoldersharedpath");
        } else if (ENV.trim().equalsIgnoreCase("dev1")) {
            DATA_TABLE_FILE_PATH = base.Config.DATATABLE_ROOT_PATH + DATA_TABLE_FILE_NAME_QA;
            System.out.println("dev Data table path: " + DATA_TABLE_FILE_PATH);
            base.Config.DATATABLE_FILE_PATH = DATA_TABLE_FILE_PATH;
            URL = pro.getProperty("dev1.url");
            userName = pro.getProperty("dev1.username");
            passWord = pro.getProperty("dev1.password");
            PreSaluserName = pro.getProperty("qa.PreSaleurname");
            PreSalpassWord = pro.getProperty("qa.PreSalepassword");
            PSAuserName = pro.getProperty("qa.PSAusername");
            PSApassWord = pro.getProperty("qa.PSApassword");
            UW4userName = pro.getProperty("qa.UW4username");
            UW3userName = pro.getProperty("qa.UW3username");
            UW2userName = pro.getProperty("qa.UW2username");
            UW1userName = pro.getProperty("qa.UW1username");
            UnderwritingName = pro.getProperty("qa.UnderwritingName");
            UWTraineeuserName = pro.getProperty("qa.UWTraineeusername");
            UWAuserName = pro.getProperty("qa.UWAssistantusername");
            UWpassword = pro.getProperty("qa.UWpassword");
            ConservationAnalystuserName = pro.getProperty("qa.ConservationAnalystusernam");
            ConservationAnalystpassWord = pro.getProperty("qa.ConservationAnalystpassword");
            SSOAdminuserName = pro.getProperty("qa.ssoAdminusername");
            UW1_UserName = pro.getProperty("qa.uw1.username");
            UW1_Pwd = pro.getProperty("qa.uw1.password");
            UW2_UserName = pro.getProperty("qa.uw2.username");
            UW2_Pwd = pro.getProperty("qa.uw2.password");
            SSOSuperuserName = pro.getProperty("qa.ssoSuperusername");
            SSOpassWord = pro.getProperty("qa.ssopassword");
            RB_PreSales_UN = pro.getProperty("qa.presalsebasic.username");
            RB_PreSales_Pwd = pro.getProperty("qa.presalsebasic.password");
            RB_SalesRepIndividual_UN = pro.getProperty("qa.salesrepindividual.username");
            RB_SalesRepIndividual_Pwd = pro.getProperty("qa.salesrepindividual.password");
            RB_Underwriting1_UN = pro.getProperty("qa.Underwriting1.username");
            RB_Underwriting1_Pwd = pro.getProperty("qa.Underwriting1.password");
            RB_SystemAdmin_UN = pro.getProperty("qa.sysadmin.username");
            RB_SystemAdmin_Pwd = pro.getProperty("qa.sysadmin.password");
            RB_SuperUser_UN = pro.getProperty("qa.superuser.username");
            RB_SuperUser_Pwd = pro.getProperty("qa.superuser.password");
            RB_SalesRepRSO_UN = pro.getProperty("qa.salesreprso.username");
            RB_SalesRepRSO_Pwd = pro.getProperty("qa.salesreprso.password");
            RB_SalesRepRegion_UN = pro.getProperty("qa.salesrepsalesrepregion.username");
            RB_SalesRepRegion_Pwd = pro.getProperty("qa.salesrepsalesrepregion.password");
            RB_SalesRepGlobal_UN = pro.getProperty("qa.SalesRepGlobal.username");
            RB_SalesRepGlobal_Pwd = pro.getProperty("qa.SalesRepGlobal.password");
            SuperUserSSO_UN = pro.getProperty("qa.SuperUserSSO_UN.username");
            SuperUserSSO_PW = pro.getProperty("qa.SuperUserSSO_PW.password");
            rslsfURL = pro.getProperty("qa.rslsf.url");
            rslsfUN = pro.getProperty("qa.rslsf.username");
            rslsfPWD = pro.getProperty("qa.rslsf.password");
            easURL = pro.getProperty("qa.eas.url");
            easUN = pro.getProperty("qa.eas.username");
            easPWD = pro.getProperty("qa.eas.password");
            pacsDBDriver = pro.getProperty("qa.PACS.DB.driver");
            pacsDBUN = pro.getProperty("qa.PACS.DB.username");
            pacsDBPWD = pro.getProperty("qa.PACS.DB.password");
            pacsDBURLr = pro.getProperty("qa.PACS.DB.url");
            apsDBDriver = pro.getProperty("qa.APS.DB.driver");
            apsDBUN = pro.getProperty("qa.APS.DB.username");
            apsDBPWD = pro.getProperty("qa.APS.DB.password");
            apsDBURLr = pro.getProperty("qa.APS.DB.url");
            vueDBDriver = pro.getProperty("qa.VUE.DB.driver");
            vueDBUN = pro.getProperty("qa.VUE.DB.username");
            vueDBPWD = pro.getProperty("qa.VUE.DB.password");
            vueDBURLr = pro.getProperty("qa.VUE.DB.url");
            stacsinterimDBDriver = pro.getProperty("qa.STACSINTERIM.DB.driver");
            stacsinterimDBUN = pro.getProperty("qa.STACSINTERIM.DB.username");
            stacsinterimDBPWD = pro.getProperty("qa.STACSINTERIM.DB.password");
            stacsinterimDBURLr = pro.getProperty("qa.STACSINTERIM.DB.url");
            stacsDBDriver = pro.getProperty("qa.STACS.DB.driver");
            stacsDBUN = pro.getProperty("qa.STACS.DB.username");
            stacsDBPWD = pro.getProperty("qa.STACS.DB.password");
            stacsDBURLr = pro.getProperty("qa.STACS.DB.url");
            eisDBDriver = pro.getProperty("EIS.DB.driver");
            eisDBUN = pro.getProperty("EIS.DB.username");
            eisDBPWD = pro.getProperty("EIS.DB.password");
            eisDBURLr = pro.getProperty("EIS.DB.url");
//            dynamicdatafoldersharedpath = pro.getProperty("qa.e2e.dynamicdatafoldersharedpath");
            dynamicdatafoldersharedpathCV = pro.getProperty("qa.e2e.dynamicdatafoldersharedpathCV");
            dynamicdatafoldersharedpathQS = pro.getProperty("qa.e2e.q2s.dynamicdatafoldersharedpath");
            dynamicdatafoldersharedpathSB = pro.getProperty("qa.e2e.s2b.dynamicdatafoldersharedpath");
        }else {
            throw new Exception("Environment value(QA/UAT/STAGE not provided from POM, please check the POM or CLI");
  /*          URL = pro.getProperty("qa.url");
            userName=pro.getProperty("qa.username");
            passWord=pro.getProperty("qa.password");
            UW1_UserName = pro.getProperty("qa.uw1.username");
            UW1_Pwd = pro.getProperty("qa.uw1.password");
            UW2_UserName = pro.getProperty("qa.uw2.username");
            UW2_Pwd = pro.getProperty("qa.uw2.password");*/
        }
    }

    public static void main(String[] s) throws Exception {
        //Config cf=new Config();
        Config cf = new Config("QA");
        System.out.println(Config.RUN_FROM_TESTPLAN);
        Field[] fields = cf.getClass().getDeclaredFields();
        for (Field field : fields) {
            System.out.println(field.getName() + "=" + field.get(cf));
        }
        Enumeration<?> e = pro.propertyNames();
        while (e.hasMoreElements()) {
            String key = (String) e.nextElement();
            String value = pro.getProperty(key);
            System.out.println(key + "=" + value);
        }
    }
}
